# Generated by Django 6.0.3 on 2026-03-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
